# POST TEST 7 Kecerdasan Buatan - TensorFlow
## 2109106036 - Ekleccia Reydianto

### Import Library

In [1]:
import tensorflow as tf
import numpy as np

## Buatlah sebuah tensor dengan shape(5,5) dengan nilai random yang disimpan dalam variable random_tensor
### Menggunakan fungsi tf.random.uniform

In [43]:
random_tensor = tf.random.uniform(shape = (5,5), minval=1, maxval=36, dtype=tf.float32)
random_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[22.864414 , 26.441841 , 17.820984 ,  1.0081611, 17.438227 ],
       [ 4.4855604, 30.989601 , 24.170462 , 17.917677 , 29.32209  ],
       [32.867405 , 13.2619   , 31.408207 , 13.052191 , 23.918528 ],
       [32.118473 , 24.472466 , 15.036712 ,  8.89113  , 34.130573 ],
       [10.751082 , 11.451107 ,  4.723091 , 31.991714 , 16.657688 ]],
      dtype=float32)>

## Buatlah sebuah tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima dalam variable prime_tensor
### Pertama kita menentukan lebih dulu isi/bilangan prima, kemudian kita convert menggunakan fungsi tf.convert_to_tensor

In [44]:
prime_tensor = [[2, 3, 5, 7, 11], [17, 19, 23, 29, 31], [37, 41, 43, 47, 53], [59, 61, 67, 71, 73], [79, 83, 89, 97, 101]]
prime_tensor = tf.convert_to_tensor((prime_tensor), dtype=tf.float32)
print(prime_tensor)


tf.Tensor(
[[  2.   3.   5.   7.  11.]
 [ 17.  19.  23.  29.  31.]
 [ 37.  41.  43.  47.  53.]
 [ 59.  61.  67.  71.  73.]
 [ 79.  83.  89.  97. 101.]], shape=(5, 5), dtype=float32)


## Tampilkan dimensi dari kedua variable tersebut
### menggunakan syntax shape

In [45]:
print(f'Display Dimensi Variabel random_tensor = {random_tensor.shape}')
print(f'Display Dimensi Variabel prime_tensor = {prime_tensor.shape}')

Display Dimensi Variabel random_tensor = (5, 5)
Display Dimensi Variabel prime_tensor = (5, 5)


## Tampilkan hasil dari perhitungan aritmetika 2 variable tersebut (Gunakan minimal 5 operator)

### ADD (Tambah)

In [46]:
jumlah = tf.add(random_tensor, prime_tensor)
print(f' Random Tensor = \n {random_tensor}')
print('\n')
print(f' Prime Tensor = \n {prime_tensor}')
print('\n')
print(f' Hasil Random Tensor + Prime Tensor = \n {jumlah}')

 Random Tensor = 
 [[22.864414  26.441841  17.820984   1.0081611 17.438227 ]
 [ 4.4855604 30.989601  24.170462  17.917677  29.32209  ]
 [32.867405  13.2619    31.408207  13.052191  23.918528 ]
 [32.118473  24.472466  15.036712   8.89113   34.130573 ]
 [10.751082  11.451107   4.723091  31.991714  16.657688 ]]


 Prime Tensor = 
 [[  2.   3.   5.   7.  11.]
 [ 17.  19.  23.  29.  31.]
 [ 37.  41.  43.  47.  53.]
 [ 59.  61.  67.  71.  73.]
 [ 79.  83.  89.  97. 101.]]


 Hasil Random Tensor + Prime Tensor = 
 [[ 24.864414  29.441841  22.820984   8.008162  28.438227]
 [ 21.485561  49.9896    47.170464  46.91768   60.32209 ]
 [ 69.8674    54.2619    74.4082    60.052193  76.918526]
 [ 91.11847   85.472466  82.03671   79.89113  107.13057 ]
 [ 89.75108   94.45111   93.72309  128.99171  117.657684]]


### MULTIPLY (Kali)

In [47]:
perkalian = tf.multiply(random_tensor, prime_tensor)

print(f' Random Tensor = \n {random_tensor}')
print('\n')
print(f' Prime Tensor = \n {prime_tensor}')
print('\n')
print(f' Hasil Random Tensor x Prime Tensor = \n {perkalian}')

 Random Tensor = 
 [[22.864414  26.441841  17.820984   1.0081611 17.438227 ]
 [ 4.4855604 30.989601  24.170462  17.917677  29.32209  ]
 [32.867405  13.2619    31.408207  13.052191  23.918528 ]
 [32.118473  24.472466  15.036712   8.89113   34.130573 ]
 [10.751082  11.451107   4.723091  31.991714  16.657688 ]]


 Prime Tensor = 
 [[  2.   3.   5.   7.  11.]
 [ 17.  19.  23.  29.  31.]
 [ 37.  41.  43.  47.  53.]
 [ 59.  61.  67.  71.  73.]
 [ 79.  83.  89.  97. 101.]]


 Hasil Random Tensor x Prime Tensor = 
 [[  45.72883     79.32552     89.10492      7.0571275  191.8205   ]
 [  76.254524   588.8024     555.9206     519.6126     908.9848   ]
 [1216.094      543.7379    1350.5529     613.45294   1267.682    ]
 [1894.9899    1492.8204    1007.45966    631.27026   2491.5317   ]
 [ 849.3355     950.4419     420.3551    3103.1963    1682.4265   ]]


### Divide (Bagi)

In [48]:
pembagian = tf.divide(random_tensor, prime_tensor)
print(f' Random Tensor = \n {random_tensor}')
print('\n')
print(f' Prime Tensor = \n {prime_tensor}')
print('\n')
print(f' Hasil Random Tensor \ Prime Tensor = \n {pembagian}')

 Random Tensor = 
 [[22.864414  26.441841  17.820984   1.0081611 17.438227 ]
 [ 4.4855604 30.989601  24.170462  17.917677  29.32209  ]
 [32.867405  13.2619    31.408207  13.052191  23.918528 ]
 [32.118473  24.472466  15.036712   8.89113   34.130573 ]
 [10.751082  11.451107   4.723091  31.991714  16.657688 ]]


 Prime Tensor = 
 [[  2.   3.   5.   7.  11.]
 [ 17.  19.  23.  29.  31.]
 [ 37.  41.  43.  47.  53.]
 [ 59.  61.  67.  71.  73.]
 [ 79.  83.  89.  97. 101.]]


 Hasil Random Tensor \ Prime Tensor = 
 [[11.432207    8.813947    3.5641968   0.14402302  1.5852933 ]
 [ 0.2638565   1.6310316   1.0508896   0.6178509   0.94587386]
 [ 0.8883082   0.32346097  0.7304234   0.27770618  0.45129296]
 [ 0.5443809   0.40118796  0.22442853  0.12522718  0.4675421 ]
 [ 0.13608965  0.13796514  0.05306844  0.32981148  0.1649276 ]]


### Subtract (Kurang)

In [49]:
pengurangan= tf.subtract(random_tensor, prime_tensor)

print(f' Random Tensor = \n {random_tensor}')
print('\n')
print(f' Prime Tensor = \n {prime_tensor}')
print('\n')
print(f' Hasil Random Tensor x Prime Tensor = \n {pengurangan}')

 Random Tensor = 
 [[22.864414  26.441841  17.820984   1.0081611 17.438227 ]
 [ 4.4855604 30.989601  24.170462  17.917677  29.32209  ]
 [32.867405  13.2619    31.408207  13.052191  23.918528 ]
 [32.118473  24.472466  15.036712   8.89113   34.130573 ]
 [10.751082  11.451107   4.723091  31.991714  16.657688 ]]


 Prime Tensor = 
 [[  2.   3.   5.   7.  11.]
 [ 17.  19.  23.  29.  31.]
 [ 37.  41.  43.  47.  53.]
 [ 59.  61.  67.  71.  73.]
 [ 79.  83.  89.  97. 101.]]


 Hasil Random Tensor x Prime Tensor = 
 [[ 20.864414   23.441841   12.820984   -5.991839    6.4382267]
 [-12.51444    11.989601    1.1704617 -11.082323   -1.6779099]
 [ -4.132595  -27.7381    -11.591793  -33.947807  -29.081472 ]
 [-26.881527  -36.527534  -51.963287  -62.10887   -38.869427 ]
 [-68.24892   -71.54889   -84.27691   -65.008286  -84.342316 ]]


## Tampilkan nilai maksimal dan minimal dari variable random_tensor
#### Menggunakan argmax() dan argmin()

In [50]:
arg_max_sample = random_tensor
print("input tensor: \n",arg_max_sample.numpy())
max_random_tensor = tf.argmax(random_tensor, axis=0)
max_random_tensor2 = tf.argmax(random_tensor, axis=1)
print("maximum value by column:",max_random_tensor.numpy())
print("maximum value by row:",max_random_tensor2.numpy())

print('\n=========================================================\n')

arg_min_sample = random_tensor
print("input tensor: \n",arg_min_sample.numpy())
min_random_tensor = tf.argmax(random_tensor, axis=0)
min_random_tensor2 = tf.argmax(random_tensor, axis=1)
print("minimum value by column:",min_random_tensor.numpy())
print("minimum value by row:",min_random_tensor2.numpy())

input tensor: 
 [[22.864414  26.441841  17.820984   1.0081611 17.438227 ]
 [ 4.4855604 30.989601  24.170462  17.917677  29.32209  ]
 [32.867405  13.2619    31.408207  13.052191  23.918528 ]
 [32.118473  24.472466  15.036712   8.89113   34.130573 ]
 [10.751082  11.451107   4.723091  31.991714  16.657688 ]]
maximum value by column: [2 1 2 4 3]
maximum value by row: [1 1 0 4 3]


input tensor: 
 [[22.864414  26.441841  17.820984   1.0081611 17.438227 ]
 [ 4.4855604 30.989601  24.170462  17.917677  29.32209  ]
 [32.867405  13.2619    31.408207  13.052191  23.918528 ]
 [32.118473  24.472466  15.036712   8.89113   34.130573 ]
 [10.751082  11.451107   4.723091  31.991714  16.657688 ]]
minimum value by column: [2 1 2 4 3]
minimum value by row: [1 1 0 4 3]


## Tampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)
### MEnggunakan syntax concat()

In [51]:
concat = tf.concat([random_tensor, prime_tensor], axis=1)
concat.numpy()

print(f' Random Tensor = \n {random_tensor}')
print('\n')
print(f' Prime Tensor = \n {prime_tensor}')
print('\n')
print(f' Hasil Gabungan Random Tensor dan Prime Tensor = \n {concat}')

 Random Tensor = 
 [[22.864414  26.441841  17.820984   1.0081611 17.438227 ]
 [ 4.4855604 30.989601  24.170462  17.917677  29.32209  ]
 [32.867405  13.2619    31.408207  13.052191  23.918528 ]
 [32.118473  24.472466  15.036712   8.89113   34.130573 ]
 [10.751082  11.451107   4.723091  31.991714  16.657688 ]]


 Prime Tensor = 
 [[  2.   3.   5.   7.  11.]
 [ 17.  19.  23.  29.  31.]
 [ 37.  41.  43.  47.  53.]
 [ 59.  61.  67.  71.  73.]
 [ 79.  83.  89.  97. 101.]]


 Hasil Gabungan Random Tensor dan Prime Tensor = 
 [[ 22.864414   26.441841   17.820984    1.0081611  17.438227    2.
    3.          5.          7.         11.       ]
 [  4.4855604  30.989601   24.170462   17.917677   29.32209    17.
   19.         23.         29.         31.       ]
 [ 32.867405   13.2619     31.408207   13.052191   23.918528   37.
   41.         43.         47.         53.       ]
 [ 32.118473   24.472466   15.036712    8.89113    34.130573   59.
   61.         67.         71.         73.       ]
 [ 1

## Tampilkan hasil sorting dari kedua variable di atas. (descending)

In [55]:
sort_prime = tf.sort(random_tensor, direction="DESCENDING")

print('========================================')
print('Hasil Sorting RANDOM TENSOR per Baris')
print('========================================')
print(sort_prime)

Hasil Sorting RANDOM TENSOR per Baris
tf.Tensor(
[[26.441841  22.864414  17.820984  17.438227   1.0081611]
 [30.989601  29.32209   24.170462  17.917677   4.4855604]
 [32.867405  31.408207  23.918528  13.2619    13.052191 ]
 [34.130573  32.118473  24.472466  15.036712   8.89113  ]
 [31.991714  16.657688  11.451107  10.751082   4.723091 ]], shape=(5, 5), dtype=float32)


In [56]:
sort_prime = tf.sort(prime_tensor, direction="DESCENDING")

print('========================================')
print('Hasil Sorting PrimeTensor TENSOR per Baris')
print('========================================')
print(sort_prime)

Hasil Sorting PrimeTensor TENSOR per Baris
tf.Tensor(
[[ 11.   7.   5.   3.   2.]
 [ 31.  29.  23.  19.  17.]
 [ 53.  47.  43.  41.  37.]
 [ 73.  71.  67.  61.  59.]
 [101.  97.  89.  83.  79.]], shape=(5, 5), dtype=float32)
